### ISSUE TITLE
Can't locate DBD/oracle.pm

### ISSUE THREAD

**Issue by omerta** [Guy-Incognito/ora2pg#1]
Hello, I have had the next error when I try to run the image:

`
install_driver(oracle) failed: Can't locate DBD/oracle.pm in @INC (you may need to install the DBD::oracle module) (@INC contains: /usr/local/lib/perl5/site_perl/5.28.1/x86_64-linux-gnu /usr/local/lib/perl5/site_perl/5.28.1 /usr/local/lib/perl5/vendor_perl/5.28.1/x86_64-linux-gnu /usr/local/lib/perl5/vendor_perl/5.28.1 /usr/local/lib/perl5/5.28.1/x86_64-linux-gnu /usr/local/lib/perl5/5.28.1) at (eval 15) line 3.
Perhaps the DBD::oracle perl module hasn't been fully installed,
or perhaps the capitalisation of 'oracle' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Mem, Oracle, Proxy, Sponge.
 at /usr/local/lib/perl5/site_perl/5.28.1/Ora2Pg.pm line 1624.
`

Thanks.

**Comment by omerta** [comment]
I had an error in the config file.

Sorry.

**Comment by pcrdll** [comment]
Hello!!! . do you remember what error? I'm fighting against the same error.
