### ISSUE TITLE
Ora2Pg UI

### ISSUE THREAD

**Issue by pgoldtho** [Guy-Incognito/ora2pg#10]
@Guy-Incognito, this is not really and issue. I couldn't figure out another way to make contact. I'm using georgmoser/ora2pg as a base image in a project that delivers a UI for Ora2Pg: https://hub.docker.com/r/visulate/visulate-ora2pg. 

I thought you might be interested. Comments and suggestions welcome.

Peter

**Comment by Guy-Incognito** [comment]
Hi @pgoldtho,
I put a link to your project in my Readme.
Thank you!
Georg
