### ISSUE TITLE
docker run failing

### ISSUE THREAD

**Issue by Yasir1811** [Guy-Incognito/ora2pg#14]
Hi,
I have created the image successfully but when I try to run the image, the container is not coming up
can you please help in this?

docker run d_ora2pg:v2

Loading DB routines from perl5db.pl version 1.60
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

main::(-e:1):   0
  DB<1> 

Below is Docker file:

FROM perl:slim

ARG ORA2PG_VERSION=23.0

# ugly fix for "update-alternatives" missing directories in slim image
RUN mkdir -p /usr/share/man/man1 &&\
    mkdir -p /usr/share/man/man7
RUN apt-get update && apt-get install -y -q --no-install-recommends \
        unzip \
        curl \
        ca-certificates \
        rpm \
        alien \
        libaio1 \
        # Install postgresql
        postgresql-client \
        # Install mysql
        libdbd-mysql \
        #install Perl Database Interface
        libdbi-perl \
        bzip2 \
        libpq-dev \
        libdbd-pg-perl

ENV ORACLE_HOME=/usr/lib/oracle/12.2/client64
ENV TNS_ADMIN=/usr/lib/oracle/12.2/client64/network/admin
ENV LD_LIBRARY_PATH=/usr/lib/oracle/12.2/client64/lib
ENV PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/oracle/12.2/client64/bin

# Install Oracle Client
RUN mkdir /usr/lib/oracle/12.2/client64/network/admin -p

COPY oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm /tmp
COPY oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm /tmp
COPY oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm /tmp
RUN alien -i /tmp/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm &&\
    alien -i /tmp/oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm &&\
alien -i /tmp/oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm

# Install ora2pg

COPY DBD-Oracle-1.74.tar.gz /tmp
COPY v23.0.zip /tmp

RUN  perl -MCPAN -e 'install DBD::Oracle' &&\
     perl -MCPAN -e 'install DBI' &&\
     perl -MCPAN -e 'install DBD::Pg' &&\
     perl -MCPAN -e 'install DBD::Oracle' &&\
     perl -MCPAN -e 'install Bundle::Compress::Zlib'

#RUN cd /tmp && tar -zxvf /tmp/DBD-Oracle-1.74.tar.gz && \
#cd /tmp/DBD-Oracle-1.74 && perl Makefile.PL -l && make && make install

RUN cd /tmp && unzip v23.0.zip  && rm -f v23.0.zip  &&\
            mv /tmp/ora2pg* /tmp/ora2pg &&\
            (cd /tmp/ora2pg && perl Makefile.PL && make && make install)

RUN mkdir /sql
        RUN mkdir /zip
        RUN mkdir /tmp/generated_ddl

        # prepare config
        ENV HOST=host
        ENV PORT=port
        ENV SERVICE_NAME=service_name
        ENV USER=user
        ENV PASSWORD=password
        ENV SCHEMA=schema

**Comment by Guy-Incognito** [comment]
Hi!
Sorry for taking so long.
I ran my tests for the current release (v23) again and everything seems to be working fine.
I'm not sure I understand what you are trying to do here? Maybe tell me what you want to achieve, so I can help!

**Comment by Guy-Incognito** [comment]
I am closing this for lack of reply.
