### ISSUE TITLE
Missing DBD::Oracle module with built ora2pg v23

### ISSUE THREAD

**Issue by nistvan86** [Guy-Incognito/ora2pg#15]
As v23 is not released on Docker Hub (is there a particular reason for this?), I'm trying to build it on my own, I've used the command:

`docker build https://github.com/Guy-Incognito/ora2pg.git#23.0 -t ora2pg:23`

If I try to use the resulting image it says:

```
install_driver(Oracle) failed: Can't locate DBD/Oracle.pm in @INC (you may need to install the DBD::Oracle module) (@INC contains: /usr/local/lib/perl5/site_perl/5.34.0/x86_64-linux-gnu /usr/local/lib/perl5/site_perl/5.34.0 /usr/local/lib/perl5/vendor_perl/5.34.0/x86_64-linux-gnu /usr/local/lib/perl5/vendor_perl/5.34.0 /usr/local/lib/perl5/5.34.0/x86_64-linux-gnu /usr/local/lib/perl5/5.34.0) at (eval 13) line 3.
Perhaps the DBD::Oracle perl module hasn't been fully installed,
or perhaps the capitalisation of 'Oracle' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Mem, Pg, Proxy, Sponge.
 at /usr/local/lib/perl5/site_perl/5.34.0/Ora2Pg.pm line 1901.
```

I'm not a Perl expert so sadly I have no idea where this goes sideways. Attaching the whole build log. [ora2pg23_build.log](https://github.com/Guy-Incognito/ora2pg/files/7977941/ora2pg23_build.log)
If you could publish a working image to Docker Hub that would be great help as well.

**Comment by Guy-Incognito** [comment]
Hi @nistvan86,
Unfortunately Docker Hub does not support building from Github (in its free version) anymore. Thanks for telling me.
I will find another solution.
Concerning the issue with your image. I will check once i fixed the Docker Hub deployment

**Comment by nistvan86** [comment]
Maybe you could use Github's own [Container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) (ghcr.io)? It seems to be available in the free tier.

**Comment by Guy-Incognito** [comment]
AFAIK ghcr.io only offers very limited traffic / storage in free tier..
FYI: I have pushed v23 to the "latest" tag. Still working on pushing individual tags.

**Comment by Guy-Incognito** [comment]
@nistvan86 Pushing to docker hub is working again. Tag "23.0" is now available:
docker pull georgmoser/ora2pg:23.0
Can you please check if you still get the same error?

**Comment by nistvan86** [comment]
Tried and your image gives me the same error message; it lists the drivers and Oracle is not in the list.

**Comment by Guy-Incognito** [comment]
There seems to be an issue with DBD::Oracle@1.83. I have pinned the version to DBD::Oracle@1.82.
Now everything works as expected.

**Comment by nistvan86** [comment]
Just chiming in that it's working correctly on my side too; repulled the Docker image. Thank you for the quick fix! 🎉
