### ISSUE TITLE
ora2pg.conf not updated with each release

### ISSUE THREAD

**Issue by matthers** [Guy-Incognito/ora2pg#21]
the ora2pg.conf file you provided is not consistent with the conf file generated by ora2pg in the Make script. There are a few differences between what you provide(and it's available in the docker container) and what is in the current version of ora2pg.

It would be great if it could be updated as it gets build.

**Comment by Guy-Incognito** [comment]
Thanks! You are correct. I will fix this when i find the time :+1:

**Comment by Guy-Incognito** [comment]
I have pushed the correct config file for the current version and will continue to do so for each release
